/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RhythmDFT: typeof import('./src/components/RhythmDFT.vue')['default']
    RhythmSelector: typeof import('./src/components/RhythmSelector.vue')['default']
  }
}
